Fix 113 - Async callbacks not returning final answer when streaming and cache enabled.
ajndkr/lanarky pull request #117
Opened 2023-08-15 23:32 UTC by auxon

## Description

Async streaming callbacks were not returning the final answer when langchain.llm_cache was set, and not streaming tokens because the answer was cached.  This PR fixes the issue and updates some tests to check when caching is enabled, that the answer is returned by the callbacks.

Fixes # 133

### Changelog:

* Fixed Async callback handling when streaming and cache is enabled to return final answer.
* Added settings.json and .flake8 config to .gitignore.
* Updated BaseRetrievalQAStreamingJSONResponse to not inherit from StreamingJSONResponse, because it adds an extra empty token to the output for no reason.
* Added AnswerStreamingJSONResponse to add answer to the output.
* Added llm_cache_enabled and llm_cache_used properties to AsycLanarkyCallback.

2023-08-16 02:29 UTC, auxon commented
I am not sure how to associate this pull request with issue 113 after creating it.

2023-08-16 08:06 UTC, ajndkr requested changes
minor suggestions but overall looks good!

2023-08-16 08:06 UTC, ajndkr commented on lanarky/callbacks/llm.py
> +ANSWER_KEY = "answer"
i think this should be a parameter for the callback in case someone uses a different output key.

2023-08-16 08:06 UTC, ajndkr commented on lanarky/callbacks/llm.py
> +        )
```suggestion
        if self.llm_cache_used: # cache missed (or was never enabled) if we are here
            self.llm_cache_used = False
```

minor optimisation. can be applied elsewhere too.

2023-08-16 08:06 UTC, ajndkr commented on lanarky/callbacks/retrieval_qa.py
> +            await AsyncLLMChainStreamingCallback.on_chain_end(self, outputs, **kwargs)
we can use `super` here.

2023-08-17 17:59 UTC, ajndkr approved these changes
lgtm!! 🥳

2023-08-17 17:59 UTC, merged